### ISSUE TITLE
How is authentication to the API handled? No personal access token support

### ISSUE THREAD

**Issue by canha** [mgedmin/cloneall#6]
Hi there.

I can't find any reference in the documentation or code related to a personal access token to authenticate against the Github API. Am I missing something obvious?

Thank you.

**Comment by mgedmin** [comment]
No, I'm using anonymous access.  This means, of course, that ghcloneall is only suitable for cloning open source repositories that are publicly available.  On the plus side, ghcloneall doesn't require tedious initial setup.

If you need to list and clone private repositories, check out alternative tools, like https://github.com/asottile/all-repos.

**Comment by canha** [comment]
Hey @mgedmin. Thanks for the quick reply, that clarifies it.
