### ISSUE TITLE
clone private repositories

### ISSUE THREAD

**Issue by jugmac00** [mgedmin/cloneall#8]
In #6 you wrote...

> No, I'm using anonymous access.  This means, of course, that ghcloneall is only suitable for cloning open source repositories that are publicly available.  

1. oh no!
2. how does this go together with the optional argument "--include-private     include private repositories (default)"? (see readme)

**Comment by mgedmin** [comment]
LOL, I just wasn't thinking when I wrote [the commit](https://github.com/mgedmin/ghcloneall/commit/7552ba8387b9488bcf2eeaf989102923ad3da503!).

I was generalizing the [filtering of archived repos and forks](https://github.com/mgedmin/ghcloneall/commit/f4499aabe189094ac74694c5e874c16ffe40c304), and I looked at all the boolean flags in the JSON structure and added options to filter on each of them.

Anyway, it shouldn't be too difficult to add support for authenticating with a token stored in a config file, if there's demand.
